### ISSUE TITLE
VIVEArcadeTool 0.8.6 stops running when SteamVR is closed

### ISSUE THREAD

**Issue by kw432** [alsoknownasfoo/ViveArcadeTool#7]
**Issue**: When SteamVR is closed and then opened on a Windows 10 PC, the VIVEArcadeTool.exe version 0.8.6 stops running.

**Steps to Replicate**:
1. Verify VIVEArcadeTool.exe is running.
2. Switch off the HMD
3. Close SteamVR (i.e. `taskkill /IM vrmonitor.exe /F`)
4. Switch on the HMD (A 5 second period has elapsed from when it was switched off.)
5. Start SteamVR (A 20 second period has elapsed from when it was closed.)
6. Check to see if VIVEArcadeTool.exe is still running.

**System Info**:
1. Windows 10 Pro
2. SteamVR Version 1.2.10 (1548804153)

**Log.txt output**: 
1. At around 14:43:05 - The tool was started successfully.
2. At around 14:43:59 - I Stopped SteamVR. (~20sec later, it was started back up)
3. At around 14:44:02 - The VIVEArcadeTool stopped.
(This was replicated at different time intervals and the issue persisted.)
> 2019-06-20 14:43:04.8251|INFO|LOG|[UMD] Update Manager initiated - https://github.com/alsoknownasfoo/ViveArcadeTool
2019-06-20 14:43:04.8604|INFO|LOG|[OVR] OpenVR Manager initiated
2019-06-20 14:43:04.8604|INFO|LOG|[HDM] HID Device Manager successfully initiated
2019-06-20 14:43:04.9073|INFO|LOG|[CPM] GetSteamVRPaths Complete
2019-06-20 14:43:04.9073|INFO|LOG|[CPM] Chaperone Manager successfully initiated
2019-06-20 14:43:05.2319|INFO|LOG|[***] VIVE Arcade Tool successfully started.
2019-06-20 14:43:05.2319|INFO|LOG|[UMD] UpdateApp() complete
2019-06-20 14:43:09.4506|INFO|LOG|[HID] disableDevice: Device acquired: USB\VID_0BB4&PID_0309\207A315D4B53
2019-06-20 14:43:09.5584|INFO|LOG|[HID] disableDevice: Device disabled: USB\VID_0BB4&PID_0309\207A315D4B53
2019-06-20 14:43:09.5584|INFO|LOG|[***] cbDisableAudioControl: Un-checked
2019-06-20 14:43:09.5584|INFO|LOG|[HID] enableDevice: Device acquired: USB\VID_0BB4&PID_0309\207A315D4B53
2019-06-20 14:43:09.7748|INFO|LOG|[HID] enableDevice: Device enabled: USB\VID_0BB4&PID_0309\207A315D4B53
2019-06-20 14:43:09.7817|INFO|LOG|[***] cbDisableAudioControl: Un-checked
2019-06-20 14:43:09.7817|INFO|LOG|[HID] enableDevice: Device acquired: USB\VID_0BB4&PID_0309\207A315D4B53
2019-06-20 14:43:09.7817|INFO|LOG|[HID] enableDevice: Device enabled: USB\VID_0BB4&PID_0309\207A315D4B53
2019-06-20 14:43:10.1966|INFO|LOG|[OVR] syncAudioDevices() - Success: 
	Playback:ITE. E2220HD (NVIDIA High Definition Audio)  Mirror:Speakers (VIVE Pro Mutimedia Audio)  Record:Microphone (VIVE Pro Mutimedia Audio)
2019-06-20 14:43:11.0952|INFO|LOG|[OVR] syncAudioDevices() - Success: 
	Playback:ITE. E2220HD (NVIDIA High Definition Audio)  Mirror:Speakers (VIVE Pro Mutimedia Audio)  Record:Microphone (VIVE Pro Mutimedia Audio)
2019-06-20 14:43:59.8412|ERROR|LOG|[OVR] processVREvents() - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at OpenVRManager.processVREvents()
2019-06-20 14:44:02.1277|ERROR|LOG|[OVR] syncAudioDevices() - ITE. E2220HD (NVIDIA High Definition Audio) : System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenVRManager.syncAudioDevices(pair<std::basic_string<char\,std::char_traits<char>\,std::allocator<char> >\,std::basic_string<char\,std::char_traits<char>\,std::allocator<char> > >* pPlaybackDevice, pair<std::basic_string<char\,std::char_traits<char>\,std::allocator<char> >\,std::basic_string<char\,std::char_traits<char>\,std::allocator<char> > >* pMirrorDevice, pair<std::basic_string<char\,std::char_traits<char>\,std::allocator<char> >\,std::basic_string<char\,std::char_traits<char>\,std::allocator<char> > >* pRecordDevice)

**Comment by alsoknownasfoo** [comment]
Issue should be fixed in https://github.com/alsoknownasfoo/ViveArcadeTool/tree/0.8.7

@kw432 Can you test and confirm this?

**Comment by kw432** [comment]
@alsoknownasfoo I can confirm that 0.8.7 has fixed the issue. Thank you.
